# Generated by Django 5.2.2 on 2025-07-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_surveytemplate_survey_owner_delete_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='allow_multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='ype',
            field=models.CharField(default='text', max_length=50),
        ),
    ]
