# Generated by Django 5.2.2 on 2025-07-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_rename_ype_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='template_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
