# Generated by Django 5.2.2 on 2025-07-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_branding'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_saved_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=50),
        ),
    ]
